### ISSUE TITLE
🔷 [Epic] Agent Directory Prototype

### ISSUE THREAD

**Issue by gabehamilton** [near/ai-platform#2]
A Directory of Custom GPTs with many advantages over other agent frameworks.

1. Decentralized Frontend.
    a. the directory, for discoverability 
    b. an 'Agent template' BOS Component, "fork this to create your Agent / Custom GPT"
3. Examples of interacting with NEAR. Signed in users can interact with social.near or other contracts as normal.
4. Additional Framework features. We'll build more features for the Agent Framework down the road.

### Agent Template Component(s)
1. Model selection. A selector for where to send LLM requests. 
    a. Start with OpenAI api and local. 
    b. credentials in local storage?
    c. Ability to register your LLM in the list of all LLMs, possibly with defining an adapter for its API
2. Pure GPT adaptors: 
    a. system prompt 
    b. text processing of results
    c. standard output component

### Additional Framework Features
1. Support for external triggers, cron-based or transaction-based
2. Ability to invoke APIs or send transactions on behalf of a user

```[tasklist]
### Tasks
- [x] https://github.com/near/ai-platform/issues/3
- [x] Agent details
- [ ] https://github.com/near/ai-platform/issues/4
- [x] Minimal Model Directory
- [x] A user can choose a model to use with their Agent
- [ ] https://github.com/near/ai-platform/issues/6
- [ ] https://github.com/near/ai-platform/issues/5
- [ ] https://github.com/near/ai-platform/issues/18
- [x] List is sorted by stars, indexer counts stars
- [x] An entity can be deleted
- [x] Only store latest action in contract
- [x] Change entity namespace to near
- [x] deploy under near account
```
