### ISSUE TITLE
Entities have tags

### ISSUE THREAD

**Issue by gabehamilton** [near/ai-platform#27]
Entities can be labeled with one or more tags.
```[tasklist]
### Tasks
- [x] Tags are part of the GenericEntityConfig base fields
- [x] When creating an Entity, one or more tags can be entered
- [x] Tags are stored in the json entity creation/edit statement in the social.near contract
- [x] The entities indexer adds tags to the new/updated row in the entities table. It also increments the tag count for each tag under that entity type.
- [x] Entities can be filtered by tags.
- [x] Nexus has global tag filters
```
