### ISSUE TITLE
🔷 [Epic] AI Nexus

### ISSUE THREAD

**Issue by gabehamilton** [near/ai-platform#35]
## Goals
1. A place to find all the NEAR related AI projects
2. Users can discover, use, and customize the use of those projects.
3. Developers can discover, build with, and compose those projects.

```[tasklist]
### Tasks
- [ ] https://github.com/near/ai-platform/issues/27
- [ ] https://github.com/near/ai-platform/issues/36
- [ ] https://github.com/near/ai-platform/issues/43
- [ ] https://github.com/near/ai-platform/issues/11
- [ ] https://github.com/near/ai-platform/issues/44
- [ ] https://github.com/near/ai-platform/issues/41
- [ ] https://github.com/near/ai-platform/issues/37
- [ ] https://github.com/near/ai-platform/issues/38
- [ ] https://github.com/near/ai-platform/issues/7
- [ ] https://github.com/near/ai-platform/issues/39
- [ ] https://github.com/near/ai-platform/issues/40
- [ ] https://github.com/near/ai-platform/issues/46
- [ ] https://github.com/near/ai-platform/issues/51
- [ ] https://github.com/near/ai-platform/issues/56
- [ ] https://github.com/near/ai-platform/issues/53
- [ ] https://github.com/near/ai-platform/issues/54
```
